// ================================
// Sample Data: Demo Products & User
// ================================

import bcrypt from "bcryptjs";

export const sampleProducts = [
  {
    name: "Cotton T-Shirt",
    price: 399,
    description: "Soft 100% cotton casual wear",
    stock: 50,
    brand: "ShoppyGlobe",
    category: "Apparel",
    image: "https://img.freepik.com/premium-photo/cotton-classics-unveiling-versatility-tshirts_941561-12591.jpg",
  },
  {
    name: "Running Shoes",
    price: 2499,
    description: "Lightweight and breathable running shoes",
    stock: 20,
    brand: "FitFlex",
    category: "Footwear",
    image: "https://i.pinimg.com/736x/29/ae/5a/29ae5aade2cf7f373d4a4a52ed344999--nike-trainers-nike-sneakers.jpg",
  },
  {
    name: "Wireless Headphones",
    price: 3499,
    description: "Noise-cancelling over-ear headphones",
    stock: 15,
    brand: "SoundMax",
    category: "Electronics",
    image: "https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6572/6572447_sd.jpg",
  },
  {
    name: "Travel Backpack",
    price: 999,
    description: "Durable and water-resistant backpack",
    stock: 30,
    brand: "GearPro",
    category: "Accessories",
    image: "https://m.media-amazon.com/images/I/71UewlJZw5L._AC_SL1500_.jpg",
  },
  {
    name: "Smartwatch",
    price: 4999,
    description: "Fitness tracking smartwatch with heart rate monitor",
    stock: 25,
    brand: "TechTime",
    category: "Electronics",
    image: "https://www.yankodesign.com/images/design_news/2020/09/the-worlds-first-foldable-smartwatch-comes-with-a-4-inch-wraparound-oled-display/Nubia_flexible_foldable_display_smartwatch_01.jpg",
  },
  {
    name: "Bluetooth Speaker",
    price: 1999,
    description: "Portable speaker with deep bass",
    stock: 40,
    brand: "SoundMax",
    category: "Electronics",
    image: "https://i5.walmartimages.com/asr/a1f6e0c7-e42b-43ae-b3ce-980e16959109.90434e9998b717ab30fa4ac63173071a.jpeg",
  },
  {
    name: "Denim Jeans",
    price: 1299,
    description: "Classic slim-fit denim jeans",
    stock: 60,
    brand: "ShoppyGlobe",
    category: "Apparel",
    image: "https://th.bing.com/th/id/R.b977883b903265f8b467e46582e6260c?rik=BfWn3vuPiPEvBg&riu=http%3a%2f%2fwww.momsbudget.com%2fwp-content%2fuploads%2f2014%2f03%2fdenim-1365x2048.jpg&ehk=ACA6XbOWGRm%2bq9dIvpRr9y7vG8GhtinZB7Fgrl6aLR4%3d&risl=&pid=ImgRaw&r=0",
  },
  {
    name: "Leather Wallet",
    price: 799,
    description: "Premium leather wallet with multiple compartments",
    stock: 50,
    brand: "GearPro",
    category: "Accessories",
    image: "https://png.pngtree.com/background/20230611/original/pngtree-two-handmade-leather-wallets-on-top-of-table-picture-image_3169319.jpg",
  },
  {
    name: "Gaming Mouse",
    price: 1499,
    description: "High precision RGB gaming mouse",
    stock: 35,
    brand: "TechTime",
    category: "Electronics",
    image: "https://cdn1.dotesports.com/wp-content/uploads/2021/01/29050527/g502-hero-intro-nb.jpg",
  },
  {
    name: "Office Chair",
    price: 5999,
    description: "Ergonomic office chair with lumbar support",
    stock: 10,
    brand: "ComfortPlus",
    category: "Furniture",
    image: "https://images.furnituredealer.net/img/products/coaster/color/office%20chairs_800142-b.jpg",
  },
  {
    name: "Sunglasses",
    price: 499,
    description: "UV-protected stylish sunglasses",
    stock: 70,
    brand: "StyleMax",
    category: "Accessories",
    image: "https://facts.net/wp-content/uploads/2024/02/8-best-sunglasses-for-men-1707186039.jpg",
  },
  {
    name: "Sports Watch",
    price: 2999,
    description: "Durable sports watch with stopwatch",
    stock: 20,
    brand: "FitFlex",
    category: "Accessories",
    image: "https://tse2.mm.bing.net/th/id/OIP.LyzRryeQyoxiP1kM8g6MhwHaHa?cb=ucfimg2&ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3",
  },
  {
    name: "Laptop Backpack",
    price: 1499,
    description: "Water-resistant backpack with laptop compartment",
    stock: 25,
    brand: "GearPro",
    category: "Accessories",
    image: "https://m.media-amazon.com/images/I/91hHfRZkLMS._AC_UL1500_.jpg",
  },
  {
    name: "Wireless Keyboard",
    price: 2499,
    description: "Compact wireless keyboard with long battery life",
    stock: 30,
    brand: "TechTime",
    category: "Electronics",
    image: "https://m.media-amazon.com/images/I/71RpgYwqAiL._AC_.jpg",
  },
  {
    name: "Casual Sneakers",
    price: 1999,
    description: "Comfortable sneakers for everyday wear",
    stock: 40,
    brand: "FitFlex",
    category: "Footwear",
    image: "https://i.pinimg.com/originals/14/c3/7d/14c37d937bdaad2a39253228f5590836.jpg",
  },
  {
    name: "Formal Shirt",
    price: 899,
    description: "Slim-fit formal shirt for office wear",
    stock: 50,
    brand: "ShoppyGlobe",
    category: "Apparel",
    image: "https://i5.walmartimages.com/seo/Alimens-Gentle-Mens-Long-Sleeve-Stretch-Dress-Shirts-Casual-Button-Down-Shirt_edc62b83-98b3-4134-9e45-1891e9e48181.604f97e82bb73983f6e8f3277668c9c0.png",
  },
  {
    name: "Wireless Earbuds",
    price: 2999,
    description: "True wireless earbuds with charging case",
    stock: 35,
    brand: "SoundMax",
    category: "Electronics",
    image: "https://tse3.mm.bing.net/th/id/OIP.2v3avSuG9CVgjuPPajU1vQHaEK?cb=ucfimg2&ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3",
  },
  {
    name: "Table Lamp",
    price: 699,
    description: "LED table lamp with adjustable brightness",
    stock: 45,
    brand: "HomeGlow",
    category: "Furniture",
    image: "https://www.tronic.co.ke/cdn/shop/files/LP-0124-BK-TC-01.jpg?v=1739275035&width=5760",
  },
  {
    name: "Yoga Mat",
    price: 499,
    description: "Non-slip yoga mat for workouts",
    stock: 80,
    brand: "FitFlex",
    category: "Fitness",
    image: "https://yogabazaar.com.au/6e8450560b528b5e810bb945b6929e3b/kf/HTB1daPMJWSWBuNjSsrbq6y0mVXa8/6MM-Thick-TPE-Non-slip-Yoga-Mats-Indoor-Fitness-Tasteless-Yoga-Mat-Pilates-8-Color-Durable.jpg",
  },
  {
    name: "Coffee Mug",
    price: 299,
    description: "Ceramic coffee mug with stylish design",
    stock: 100,
    brand: "HomeGlow",
    category: "Kitchenware",
    image: "https://tse4.mm.bing.net/th/id/OIP.cavfgpnKwopcALBCWFXgjQHaF6?cb=ucfimg2&ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3",
  },
];

// Admin
export const testUser = {
  name: "Pandat Ji",
  email: "gmail@pandatji.com",
  password: "PanditJi@#$17",
};
